[window]
dynamic_padding = true
decorations = "None"
option_as_alt = "Both"

[font]
# normal = { family = "Hack Nerd Font Mono", style = "Regular" }
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular"}
size = 12


[colors.primary]
foreground = "#C4C4C4"
background = "#1B1B1B"

[colors.cursor]
cursor = "#C4C4C4"
# text = "#C4C4C4"

[colors.normal]
black = "#1B1B1B"
red = "#F16161"
green = "#7CB987"
yellow = "#DDC74C"
blue = "#6296BE"
magenta = "#BE6DEE"
cyan = "#49BAC8"
white = "#BEBEBE"

[colors.bright]
black = "#808080"
red = "#FF8985"
green = "#97D5A0"
yellow = "#FAE365"
blue = "#7DB1DA"
magenta = "#D68EFF"
cyan = "#49BAC8"
white = "#C4C4C4"

[colors.dim]
black = "#000000"
red = "#A04040"
green = "#5D7D62"
yellow = "#9E914A"
blue = "#486073"
magenta = "#7F46A1"
cyan = "#3F7F87"
white = "#898989"
